### ISSUE TITLE
Done close Vite manifest not found at

### ISSUE THREAD

**Issue by RizkyRauf** [syamsulapp/task-5-fullstack#5]
terjadi error .
Vite manifest not found at:/Belajar_Bareng/task-5-fullstack/public/build/manifest.json

resources / views / layouts / app.blade.php: 29

@vite(['resources/sass/app.scss', 'resources/js/app.js'])

**Comment by syamsulapp** [comment]
how to solve:
1. instal node v18.16.0
2. npm install
3. npm run dev || yarn dev (kalo mau pake yarn dev install dulu : npm install yarn --global)
4. solved this
5. php artisan serve -> langsung bisa kebuka appsnya dan udah bisa langsung login dan register


jangan lupa di migrate soalnya tbl db ada disitu semua, config .env sesuaikan dengan di local masing2
kalo mau delpoy di server ntar ane siapin oke

**Comment by syamsulapp** [comment]
> terjadi error . Vite manifest not found at:/Belajar_Bareng/task-5-fullstack/public/build/manifest.json
> 
> resources / views / layouts / app.blade.php: 29
> 
> @Vite(['resources/sass/app.scss', 'resources/js/app.js'])

jadi projectnya butuh node jsjg  mas rauf soalnya pake vite, vite itu adalah local server dev vue, sudah pasti butuh node js
dan nanti kalo nanti vue nya mau di include kan kedalam laravel udah bisa tuh karena udah ada serve dev vue di dalam laravelnya, tapi nanti aja lah yah kecuali udah butuh baru kita implement

**Comment by syamsulapp** [comment]
> terjadi error . Vite manifest not found at:/Belajar_Bareng/task-5-fullstack/public/build/manifest.json
> 
> resources / views / layouts / app.blade.php: 29
> 
> @Vite(['resources/sass/app.scss', 'resources/js/app.js'])

mohon di cek kembali mas rauf harusnya sudah terslove itu

**Comment by syamsulapp** [comment]
kalo sudah done close issue aja yah

**Comment by RizkyRauf** [comment]
done close

**Comment by syamsulapp** [comment]
ok mas rauf
