### ISSUE TITLE
SQLSTATE[HY000]General error: 1364 Field 'role' doesn't have a default value

### ISSUE THREAD

**Issue by RizkyRauf** [syamsulapp/task-5-fullstack#7]
![Screenshot from 2023-06-05 15-21-27](https://github.com/syamsulapp/task-5-fullstack/assets/95733130/4f052a83-3a7b-4986-ac28-d8d481ff168c)

![Screenshot from 2023-06-05 15-24-43](https://github.com/syamsulapp/task-5-fullstack/assets/95733130/6e60513e-b711-4445-b62c-af50e726b1be)

apakah hal tersebut karena bentrok dengan database saya sebelumnya..?

**Comment by syamsulapp** [comment]
> ![Screenshot from 2023-06-05 15-21-27](https://user-images.githubusercontent.com/95733130/243295215-4f052a83-3a7b-4986-ac28-d8d481ff168c.png)
> 
> ![Screenshot from 2023-06-05 15-24-43](https://user-images.githubusercontent.com/95733130/243295375-6e60513e-b711-4445-b62c-af50e726b1be.png)
> 
> apakah hal tersebut karena bentrok dengan database saya sebelumnya..?

migrate ulang mas rauf

**Comment by syamsulapp** [comment]
@RizkyRauf migrate ulang aja mas

**Comment by RizkyRauf** [comment]
![Screenshot from 2023-06-05 15-59-28](https://github.com/syamsulapp/task-5-fullstack/assets/95733130/3e97f07a-ccc6-42ff-9a19-5ef5431c5487)

**Comment by RizkyRauf** [comment]
![Uploading Screenshot from 2023-06-05 16-00-48.png…]()

**Comment by RizkyRauf** [comment]
![Uploading Screenshot from 2023-06-05 16-02-59.png…]()

**Comment by RizkyRauf** [comment]
![Screenshot from 2023-06-05 16-02-59](https://github.com/syamsulapp/task-5-fullstack/assets/95733130/706ffd97-8735-4207-b2f7-5c1a78ea915f)

**Comment by RizkyRauf** [comment]
![Screenshot from 2023-06-05 16-03-56](https://github.com/syamsulapp/task-5-fullstack/assets/95733130/58ef1ac4-948f-409c-a9d6-9bb5857517da)

**Comment by RizkyRauf** [comment]
done #5

**Comment by syamsulapp** [comment]
ok, saya close yah
